chapters = [
            "Ultramarines", 
            "Space Wolves", 
            "White Scars",
            "Blood Angels",
            "Salamanders",
            "Dark Angels",
            "Imperial Fists",
            "Iron Hands",
            "Raven Guard",
            "Crimson Fists",
            "Blood Ravens",
            "Howling Griffons",
            "Black Templars",
            "Lementers",
            "Novamarines",
            "Carcarodons",
            "Brazen Claws",
            "Death Eagles",
            "Red Talons",
            "Angels of Vengence",
            "Angels of Absolution",
            "Flesh Tearers",
            "Storm Giants",
            "Storm Lords",
            "Storm Wardens",
            "Raptors",
            "Silver Skulls",
            "Iron Snakes",
            "Mantis Warriors"]